#!/bin/sh
set -e
export GO15VENDOREXPERIMENT=1
export CGO_ENABLED=0
(cd cmd/server && go build)
(cd cmd/control && go build)

if [ "$1" = "production" ]; then
  npm run production:build
else
  npm run build
fi
