#!/usr/bin/env bash
set -e
export GOARCH=amd64
export GOOS=linux
rm -rf dist && mkdir -p dist
cp -r templates public dist/
(cd cmd/server && go build -ldflags "-X github.com/thcyron/tracklog/pkg/server.DataDir=/usr/local/share/tracklog" -o ../../dist/tracklog-server)
(cd cmd/control && go build -o ../../dist/tracklog-control)
docker build -t thcyron/tracklog .
